name: Mastodon Post

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  MASTODON_SERVER: ${{ secrets.MASTODON_SERVER }}
  MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}

jobs:
  generate-playlist:
    name: Generate and Post Playlist
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run script
        run: python3 .github/scripts/smpost.py ${{ env.MASTODON_SERVER }} ${{ env.MASTODON_TOKEN }}
